# Generated by Django 6.0 on 2025-12-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('REVIEWER', 'Reviewer'), ('USER', 'User')], default='USER', max_length=20),
        ),
    ]
