# Generated by Django 6.0 on 2025-12-18 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('documents', '0002_document_review_comments_document_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittrail',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='audittrail',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('DOWNLOAD', 'Download'), ('VIEW', 'View'), ('SUBMIT_REVIEW', 'Submit for Review'), ('ASSIGN_REVIEWER', 'Assign Reviewer'), ('STATUS_CHANGE', 'Status Change')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['-timestamp'], name='audit_audit_timesta_ecedbd_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_a44812_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['document', '-timestamp'], name='audit_audit_documen_1e9d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action', '-timestamp'], name='audit_audit_action_2197eb_idx'),
        ),
    ]
